### ISSUE TITLE
First Simulated Device is working great but 2nd is not seen

### ISSUE THREAD

**Issue by l0ghan** [biddster/node-red-contrib-wemo-emulator#21]
hello, 
first thx very much for this node.
I've create one simulated WeMo with :
- id : 001
- port : 55555
-->my node is working great wemo is seen by Alexa and process work great

I've created another simulated WeMo with: 
- id : 002
- port : 55556
-->this WeMo sumulated device is not seen by alexa but the First one  (id : 001) still work great

Do you have any idea about that ?
Regards
julien

**Comment by biddster** [comment]
Have you tried restarting node-red and attempting detection again?

**Comment by l0ghan** [comment]
yes i've and it shows me another entrie for the first simulated WeMo.

**Comment by l0ghan** [comment]
i managed to add all my wemo emulator by adding and disable it one by one after adding them to alexa.
finally i activated all the node in node-red and it 's now OK.
It's not very convenient but it works :)
cheers

**Comment by biddster** [comment]
Thanks for the report. I don't know why this is happening. I've seen reports elsewhere of Alexa duplicating devices for other libraries, not just this one.

**Comment by martinschki** [comment]
same here,
Anything I can send to help?

Am 15. März 2018, um 21:43, schrieb biddster <notifications@github.com>:

Thanks for the report. I don't know why this is happening. I've seen reports elsewhere of Alexa duplicating devices for other libraries, not just this one.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/biddster/node-red-contrib-wemo-emulator","title":"biddster/node-red-contrib-wemo-emulator","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/biddster/node-red-contrib-wemo-emulator">https://github.com/biddster/node-red-contrib-wemo-emulator</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@biddster in #21: Thanks for the report. I don't know why this is happening. I've seen reports elsewhere of Alexa duplicating devices for other libraries, not just this one. "}],"action":{"name":"View Issue","url":"<a href="https://github.com/biddster/node-red-contrib-wemo-emulator/issues/21#issuecomment-373499555">https://github.com/biddster/node-red-contrib-wemo-emulator/issues/21#issuecomment-373499555</a>"}}}

**Comment by l0ghan** [comment]
hey  martinschki,

What i've done to achieve this : 
- make 2 tabs : 1 tab enable 1 tab disable

For each wemo simulated device : 
1 - add the wemo bloc to the enabled tab
2 - build
3 - add the wemo to alexa 
4 - move the bloc to the disabled tab

At the end enable the disable Tab with all the wemo.
Alexa should have kept all the Wemo devices :)

keep us updated 
l0ghan

**Comment by biddster** [comment]
1.0.0 is released and should fix this issue. Please reopen if that's not the case.

**Comment by nicedevil007** [comment]
Hey @biddster 

got the same issue now with version 1.0.0.

I added 5 devices and all of them are shown. That was a couple of weeks before.
Now I just added new devices and alexa isn't able to find them. And yes everything got an other ID and Port :)
